//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CollegeAdministration.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public int studentId { get; set; }
        public string studentName { get; set; }
        public string emailId { get; set; }
        public string phoneNumber { get; set; }
        public string password { get; set; }
        public string address { get; set; }
        public int courseId { get; set; }
        public int departmentId { get; set; }
        public string gender { get; set; }
        public Nullable<double> attendance { get; set; }
        public Nullable<System.DateTime> academicYear { get; set; }
        public Nullable<double> percentage { get; set; }
    
        public virtual Course Course { get; set; }
        public virtual Department Department { get; set; }
    }
}
